[package]
name = "zmake"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
zmake_lib = { path = "../zmake_lib" }

[profile.release]
strip = true
lto = true
